language: perl
sudo: false

cache:
  directories:
  - ~/perl5/perlbrew/perls

os:
  - osx

compiler:
  - clang
  - gcc

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

script:
  - sh .travis.deps.sh
after_success:
  - find -name *.gcda -type f -exec gcov-4.8 -abc -o `basename {}` {} \;
  - cover -gcov -report coveralls -ignore_re "^/usr" -ignore_re "^libsass"
